### ISSUE TITLE
Omnipay V3 Requirement

### ISSUE THREAD

**Issue by skurvish** [mikeybeck/omnipay-square#1]
Your current Composer.json file is requiring Omnipay V3. Is there some particular reason for this? The system I am working on is using V2. I was able to change the requirement and everything seems to be running fine on V2 but I may be missing something.

**Comment by mikeybeck** [comment]
Ah - I use Omnipay v3 with a couple of other gateways which is why I required v3.
I don't recall having to change anything to make it compatible so it may well work on v2 also.

**Comment by skurvish** [comment]
OK. Would it be reasonable to change the requirement to V2 in the composer file for this gateway? Your general composer file can always call for V3.

**Comment by mikeybeck** [comment]
Yep, that's no problem.  I'll update it now
